baseurl = "https://DanielChoate.github.io/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = "Daniel Choate Resume"
    subtitle = "A site built in 2 Hours"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Daniel Choate"
      logoHomeLink = "/"

    [languages.en.params.logo]
      logoText = "Daniel Choate"
      logoHomeLink = "/"
      
 [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "projects"
        url = "/projects"
        [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Home"
        url = "/posts/hello"
