baseurl = "https://danielchoate.github.io/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "red"
  showMenuItems = 2
  fullWidthTheme = true
  centerTheme = true

[languages]
  [languages.en]
    title = "Terminal"
    subtitle = "A site built in 2 Hours"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Daniel Choate"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "projects"
        url = "/projects"
        [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Home"
        url = "/posts/hello"
